### ISSUE TITLE
Clarification on appropriate wp_json_encode() usage

### ISSUE THREAD

**Issue by trepmal** [Automattic/vip-code-samples#49]
I'm trying to wrap my brain around why this is not great (just for arrays/objects? or even for strings?):

https://github.com/Automattic/vip-code-samples/blob/adeee777b3b3df6c5ec2193d5d9460149b9211e2/10-security/README.md#L81

Then, as our good example, we have this:

https://github.com/Automattic/vip-code-samples/blob/adeee777b3b3df6c5ec2193d5d9460149b9211e2/10-security/js-dynamic.php#L17-L19

To compare, here's what Core does when `wp_localize_script()` is used [[source](https://github.com/WordPress/WordPress/blob/5.2.2/wp-includes/class.wp-scripts.php#L449)]: 

```
foreach ( (array) $l10n as $key => $value ) {
    if ( ! is_scalar( $value ) ) {
        continue;
    }

    $l10n[ $key ] = html_entity_decode( (string) $value, ENT_QUOTES, 'UTF-8' );
}

$script = "var $object_name = " . wp_json_encode( $l10n ) . ';';
```

Thoughts on the difference?

**Comment by rogertheriault** [comment]
Maybe we need additional labels other than bad and good. I think the "not great" example is surely better than most others. This is a tricky topic and better techniques are still being devised...

I think the benefit of the good example is that it encodes the json as a proper string rather than inserting it as an object when it's technically at that point just a string. JSON.parse presumably does a better job and the parsing is done by the browser's JS engine?

But perhaps a bit of explanation in the README might explain, maybe we should also show what the output would look like?
